### ISSUE TITLE
Start on boot

### ISSUE THREAD

**Issue by GTP95** [cuberite/android#10]
This is a wonderful application that makes possible to run a Minecraft server on a phone, this would be impossible with the official Minecraft server! However due to the very nature of Android it would be useful to have a "Start server on boot" option inside the settings, because otherwise it's not so easy to do without the tools of a traditional server/desktop OS. For a short term workaround, is there maybe a way I can start Cuberite *and* the server using the command line?
Thanks for your help and have a nice weekend.

**Comment by mathiascode** [comment]
I'll look into this in the near future.

**Comment by GTP95** [comment]
Thanks!
