### ISSUE TITLE
Repair the server depot 

### ISSUE THREAD

**Issue by gb85150** [cuberite/android#35]
Since 2 months, the first install dépôt server was broken (ERROR 404). Thanks for your awesome work.

**Comment by mathiascode** [comment]
Builds have been broken since December 5, and will be fixed soon.

**Comment by gb85150** [comment]
https://drive.google.com/file/d/1FY8931yGy545575QRoP--FK6YJqNCB_k/view?usp=drivesdk
The video the screen of the problem (can't upload directly too heavy for github

**Comment by mathiascode** [comment]
This is now fixed.
