### ISSUE TITLE
The installation of 1.3 relase is impossible

### ISSUE THREAD

**Issue by gb85150** [cuberite/android#36]
I think the fault is the apk signature.

**Comment by mathiascode** [comment]
Any error messages? Screenshots?

**Comment by cbpwin** [comment]
uhmm how to fix this?
![Screenshot_20191229-081745](https://user-images.githubusercontent.com/59322738/71550813-de448880-2a13-11ea-8c39-6be631836312.png)

**Comment by mathiascode** [comment]
@cbpwin #35 
In the app settings, manually import server.zip and a binary zip for your architecture from here, or wait for a fix in a few days: https://builds.cuberite.org/job/cuberite/job/master/job/android/job/release/334/

armeabi-v7a.zip should work with most Android devices.
