### ISSUE TITLE
Install-button is overlapped

### ISSUE THREAD

**Issue by mathiascode** [cuberite/android#4]
When using the app in landscape mode, the install-button is overlapped.
![u3mnylx](https://cloud.githubusercontent.com/assets/8754153/22853686/a90e8e44-f065-11e6-86fa-e69fdcb7b260.png)

**Comment by ItsShadowCone** [comment]
That entirely depends on your phone, the button is in the center of the screen..... But what would you suggest? (there might be text above the button too...)

**Comment by madmaxoft** [comment]
How about changing the button to say only "console", moving both of them next to each other at the bottom of the screen, and make all the other content  fit into the rest of the space, possibly keeping the "install" button in the center *of the rest of the screen*

edit: the "install" button could probably go to the top with no problem. No need for it to be centered at all.

**Comment by mathiascode** [comment]
![center](https://cloud.githubusercontent.com/assets/8754153/22854631/83db7b76-f07b-11e6-82ce-cc900baeb36a.png)
or
![center2](https://cloud.githubusercontent.com/assets/8754153/22854633/86d5433e-f07b-11e6-8f47-bfb01925585a.png)

Is it possible to center the install button from the header down to the top of the gray buttons?

**Comment by ItsShadowCone** [comment]
Should be possible 👍 btw it's just just the install button, it's mainly start/stop.
