### ISSUE TITLE
Choose external storage as server location

### ISSUE THREAD

**Issue by hyperak** [cuberite/android#43]
Currently you can only install Cuberite in the internal storage. I don't speak for everybody, but I'm pretty sure people will likely want to have their server on their SD card due to storage limitations. I think it would be great if we were able to do so.

**Comment by mathiascode** [comment]
[app-debug.zip](https://github.com/cuberite/android/files/4021345/app-debug.zip)
Can you test this apk? Ideally, a toggle for switching to the SD card storage should appear in the settings, if storage permissions are granted and the card is mounted.

**Comment by hyperak** [comment]
Yes, and it works. Thank you very much.

**Comment by mathiascode** [comment]
Good to hear! Could you test https://github.com/cuberite/android/pull/45 too?

**Comment by hyperak** [comment]
Alright, I tested it. Both denying and allowing the storage permission work just as the initial dialog box says it. Thanks again!

**Comment by bearbin** [comment]
Closing as apparently fixed by #45

**Comment by mathiascode** [comment]
Not fixed yet.
