### ISSUE TITLE
Can't connect to server from desktop, or even access the webadmin from Xiaomi phone which is hosting

### ISSUE THREAD

**Issue by memegauste** [cuberite/android#47]
As title says, I can't connect to Cuberite from PC, or even access WebAdmin using:
```Settings -> Open Webadmin```

But it seems that server is running (I see default minecraft server output in `Console`).
My phone is Xiaomi Mi6, Android 9 with MIUI 11. I suspect there is some permission denied anywhere in port binding, but not so many people host servers on their phones and I assume it's hard to find an answer on stack / reddit.

**Comment by mathiascode** [comment]
Related: https://github.com/cuberite/cuberite/issues/4457
