### ISSUE TITLE
Cuberite won't install on LGK20+

### ISSUE THREAD

**Issue by davidm5375** [cuberite/android#55]
For some reason it wont install, even though it installed on my other phone...

It says i "need an internet connection" even though i am on github on the phone iwas trying to install cuberite on.

**Comment by mathiascode** [comment]
Is your Android version 7.0?

**Comment by davidm5375** [comment]
Yes

**Comment by mathiascode** [comment]
@bearbin Do you think we could use a 256-bit EC cert on builds.cuberite.org and download.cuberite.org instead of 384-bit? There was a regression in Android 7.0-7.1 where the SSL stack only supports the secp256r1 curve.

**Comment by bearbin** [comment]
Done, but I can't easily test as I don't have an android of the appropriate version.

**Comment by mathiascode** [comment]
I tested, it works.
@davidm5375 Can you confirm?

**Comment by davidm5375** [comment]
Ok, It looks like its working now. Thanks!
