### ISSUE TITLE
Download error | apk 1.2

### ISSUE THREAD

**Issue by ghost** [cuberite/android#6]
on click the option "DOWNLOAD AND INSTALL SERVER.ZIP" and "TOGGLE AUTHENTICATION"

![screenshot_2017-03-13-20-20-33](https://cloud.githubusercontent.com/assets/5884000/23871424/9b3cc754-082a-11e7-88a6-3144063ed751.png)

![screenshot_2017-03-13-20-26-07](https://cloud.githubusercontent.com/assets/5884000/23871590/558faf9a-082b-11e7-8802-9e715f19aaf5.png)

**Comment by ItsShadowCone** [comment]
This issue needs redesigning the whole permission workflow, appearantly never any storage location gets set. I am currently rather busy myself, but I will see when I have some time for it.

**Comment by mathiascode** [comment]
Is this still an issue? It doesn't seem to happen for me anymore since the Android builds were fixed.

**Comment by ItsShadowCone** [comment]
@mathiascode I assume your Storage location isn't empty, right?

**Comment by mathiascode** [comment]
Sorry, this is still an issue in Android 5 and below.

**Comment by izackp** [comment]
Also happens in Android 5.0.2 on the LG G2. Any option that downloads results in a download error.

**Comment by ItsShadowCone** [comment]
> This issue needs redesigning the whole permission workflow, appearantly never any storage location gets set.

As I already said it is a problem with the permission workflow so potentially applies to anythign below 6.0.

**Comment by izackp** [comment]
For me, the solution was simply to call the method to grab permissions regardless of whether or not the permission check passes. This results in the permission callback being executed and the storage location variable being set.

**Comment by mrbesen** [comment]
This issue is still happening to me, sadly i dindt saw this repo and submitted it here:
https://github.com/cuberite/cuberite/issues/4313
