### ISSUE TITLE
The program crashes when opening the settings

### ISSUE THREAD

**Issue by Lambdasond** [cuberite/android#74]
When opening the settings in the application, it crashes. Maybe it's because of Android version 13.

**Comment by theotheroracle** [comment]
it works when using internal app storage confirming its likely an android 13 storage api change

**Comment by mathiascode** [comment]
What's the model of the phone you're using?

**Comment by Lambdasond** [comment]
Manufacturer : realme
Model : RMX3085
Product : RMX3085EEA
Android Version : 13
Colour OS: 13
Realme UI: 4.0

чт, 21 бер. 2024 р., 00:00 користувач Mat ***@***.***> пише:

**Comment by theotheroracle** [comment]
oneplus 6 enchilada android 13 lineage

**Comment by mathiascode** [comment]
Any difference with this .apk? Note that you have to uninstall the F-Droid Cuberite build first.

~[app-debug.zip](https://github.com/cuberite/android/files/14715354/app-debug.zip)~

Edit: figured out what the issue is. I'll tag a 1.6.3 release as soon as possible.

**Comment by Lambdasond** [comment]
Yes, It works

пт, 22 бер. 2024 р., 03:56 користувач Mat ***@***.***> пише:

**Comment by Deeptanil** [comment]
Hey,
This issue is occuring to me as well and I'm not in android 13.
I just recently installed the app and it's crashing whilst trying to open settings.

Model: Lenovo tab 4 plus
Os: pixel experience custom rom
Android: 9
