### ISSUE TITLE
Migrate to Jetpack Compose

### ISSUE THREAD

**Issue by mathiascode** [cuberite/android#79]
Jetpack Compose is the recommended toolkit for building UIs nowadays. Attempt a port from Android Views to Jetpack Compose, to get an idea of how stable it is right now.

https://developer.android.com/codelabs/jetpack-compose-migration

**Comment by Iamlooker** [comment]
Can I help with this? I do have a little experience with Jetpack Compose. And yes, it is stable enough to be deployed in production without any issues. There are no major issues as of now and its also really concise.

**Comment by mathiascode** [comment]
Sure! Feel free to work on this. At the moment I have no experience with Jetpack Compose, but I could review your changes and get familiar with it that way.

**Comment by mathiascode** [comment]
> Can I help with this? But I have basic knowledge of Jetpack. 

Thanks for showing interest, but almost all of the migration is done at this point. It's probably better if @Iamlooker finishes his remaining work.

**Comment by mathiascode** [comment]
I still want to do thorough testing on different Android versions before the next release, but I consider this complete.

@Iamlooker Thanks again for your work! Let me know if there's still something that needs to be done.

**Comment by Iamlooker** [comment]
Migration of AndroidX navigation to Jetpack Compose Navigation is the only part which is missing, I will finish it by the end of this week then it should be ready 🧐
